"""Définitions statiques du Data Catalog national (métadonnées, pas de fetch)."""

from __future__ import annotations

from compass_core.catalog.models import DatasetRecord, QualityDimensions


def _q(**kwargs: float) -> QualityDimensions:
    return QualityDimensions(**kwargs)


def static_definitions() -> list[DatasetRecord]:
    """Catalogue de référence — statuts affinés dynamiquement par le service."""
    return [
        DatasetRecord(
            dataset_id="sentinel2",
            name="Sentinel-2",
            description="Optique multispectral Copernicus — réflectance, indices, altérations de surface.",
            source="ESA / Copernicus",
            organization="ESA / Copernicus",
            official_url="https://dataspace.copernicus.eu/",
            license="Copernicus Open Access",
            data_type="Optique multispectral",
            format="COG / STAC",
            coverage="RDC (mondiale)",
            resolution="10–20 m",
            coordinate_reference_system="EPSG:4326 / UTM scène",
            category="IMAGERIE SATELLITE",
            data_class="OPEN",
            evidence_level="OBSERVATION",
            availability="TO_CONFIGURE",
            api_available="Oui (STAC / CDSE)",
            access_method="API + credentials",
            frequency="~5 jours",
            reliability_note="Élevée (observation) — anomalie ≠ gisement",
            note="Connecteur prêt — aucune scène téléchargée automatiquement.",
            quality=_q(
                completeness=0,
                accuracy=85,
                consistency=80,
                recency=0,
                spatial_resolution=90,
                source_reliability=95,
                scientific_quality=90,
                processing_quality=50,
            ),
        ),
        DatasetRecord(
            dataset_id="sentinel1",
            name="Sentinel-1",
            description="SAR C-band — texture, humidité, structures, zones nuageuses.",
            source="ESA / Copernicus",
            organization="ESA / Copernicus",
            official_url="https://dataspace.copernicus.eu/",
            license="Copernicus Open Access",
            data_type="SAR",
            format="COG / STAC",
            coverage="RDC",
            resolution="~10–20 m",
            coordinate_reference_system="EPSG:4326 / UTM scène",
            category="IMAGERIE SATELLITE",
            data_class="OPEN",
            evidence_level="OBSERVATION",
            availability="TO_CONFIGURE",
            api_available="Oui",
            access_method="API + credentials",
            frequency="~6–12 jours",
            reliability_note="Élevée (observation radar)",
            quality=_q(
                completeness=0,
                accuracy=80,
                consistency=75,
                recency=0,
                spatial_resolution=85,
                source_reliability=95,
                scientific_quality=85,
                processing_quality=40,
            ),
        ),
        DatasetRecord(
            dataset_id="landsat",
            name="Landsat 8/9",
            description="Séries historiques multispectrales USGS.",
            source="USGS",
            organization="USGS",
            official_url="https://earthexplorer.usgs.gov/",
            license="Public domain USGS",
            data_type="Optique",
            format="GeoTIFF",
            coverage="RDC",
            resolution="30 m",
            coordinate_reference_system="UTM / WGS84",
            category="IMAGERIE SATELLITE",
            data_class="OPEN",
            evidence_level="OBSERVATION",
            availability="TO_CONFIGURE",
            api_available="Oui (EarthExplorer / M2M)",
            access_method="API / téléchargement",
            frequency="16 jours",
            reliability_note="Élevée (observation historique)",
            quality=_q(
                completeness=0,
                accuracy=80,
                consistency=80,
                recency=0,
                spatial_resolution=70,
                source_reliability=95,
                scientific_quality=85,
                processing_quality=40,
            ),
        ),
        DatasetRecord(
            dataset_id="esri_imagery",
            name="ESRI World Imagery",
            description="Fond satellite tuilé — visualisation uniquement.",
            source="Esri",
            organization="Esri",
            official_url="https://www.esri.com/",
            license="Esri (attribution)",
            data_type="Fond tuiles",
            format="XYZ",
            coverage="Mondiale",
            resolution="Variable",
            coordinate_reference_system="EPSG:3857",
            category="IMAGERIE SATELLITE",
            data_class="OPEN",
            evidence_level="OBSERVATION",
            availability="CONNECTED",
            api_available="Tuiles XYZ",
            access_method="HTTP tuiles",
            frequency="Mosaïque",
            last_data="Tuiles en ligne",
            reliability_note="Visuel uniquement — pas d'analyse spectrale",
            quality=_q(
                completeness=60,
                accuracy=50,
                consistency=60,
                recency=70,
                spatial_resolution=50,
                source_reliability=70,
                scientific_quality=30,
                processing_quality=80,
            ),
        ),
        DatasetRecord(
            dataset_id="srtm",
            name="SRTM / MNT",
            description="Modèle numérique de terrain — altitude, pente, morphométrie.",
            source="USGS / NASA",
            organization="USGS / NASA",
            official_url="https://earthexplorer.usgs.gov/",
            license="Public",
            data_type="Modèle numérique de terrain",
            format="GeoTIFF",
            coverage="RDC si téléchargé ; sinon bande élévation Kolwezi synthétique",
            resolution="30 m (SRTM) / 250 m (échantillon local)",
            coordinate_reference_system="EPSG:32733 (pilote Kolwezi)",
            category="RELIEF",
            data_class="SYNTHETIC",  # affiné dynamiquement
            evidence_level="OBSERVATION",
            availability="SYNTHETIC",
            api_available="EarthExplorer",
            access_method="Fichier local",
            frequency="Statique",
            local_path="data/rdc/kolwezi/stack_multiphysics.tif",
            reliability_note="Échantillon local synthétique tant que SRTM national absent",
            note="Ne pas confondre bande DEM du stack Kolwezi avec un MNT national SRTM.",
            quality=_q(
                completeness=15,
                accuracy=40,
                consistency=50,
                recency=30,
                spatial_resolution=40,
                source_reliability=40,
                scientific_quality=35,
                processing_quality=60,
            ),
        ),
        DatasetRecord(
            dataset_id="soilgrids",
            name="SoilGrids",
            description="Propriétés pédologiques mondiales (texture, carbone, pH, profondeur).",
            source="ISRIC",
            organization="ISRIC — World Soil Information",
            official_url="https://soilgrids.org/",
            license="CC-BY 4.0 (à confirmer pour usage opérationnel)",
            data_type="Raster pédologique",
            format="GeoTIFF / WCS",
            coverage="Mondiale / RDC",
            resolution="250 m",
            coordinate_reference_system="EPSG:4326",
            category="SOL & SOUS-SOL",
            data_class="OPEN",
            evidence_level="INTERPRETATION",
            availability="NOT_CONNECTED",
            api_available="Oui (WCS / REST)",
            access_method="API / téléchargement — non synchronisé",
            frequency="Versions ISRIC",
            reliability_note="Modèle spatial — pas une observation terrain locale",
            note="Tant que non importé : Soil = N/E (jamais dérivé de la pente).",
            quality=_q(
                completeness=0,
                accuracy=60,
                consistency=70,
                recency=50,
                spatial_resolution=55,
                source_reliability=80,
                scientific_quality=75,
                processing_quality=20,
            ),
        ),
        DatasetRecord(
            dataset_id="hwsd",
            name="HWSD (Harmonized World Soil Database)",
            description="Base sol harmonisée FAO/IIASA — unités pédologiques.",
            source="FAO / IIASA",
            organization="FAO / IIASA",
            official_url="https://www.fao.org/soils-portal/data-hub/",
            license="Selon conditions FAO",
            data_type="Raster / polygones sols",
            format="Raster / DB",
            coverage="Mondiale",
            resolution="~1 km",
            coordinate_reference_system="EPSG:4326",
            category="SOL & SOUS-SOL",
            data_class="OPEN",
            evidence_level="INTERPRETATION",
            availability="NOT_CONNECTED",
            api_available="Téléchargement",
            access_method="Fichier — non synchronisé",
            frequency="Versions rares",
            reliability_note="Résolution coarse — N/E si insuffisant pour la zone",
            quality=_q(
                completeness=0,
                accuracy=50,
                consistency=60,
                recency=30,
                spatial_resolution=30,
                source_reliability=75,
                scientific_quality=65,
                processing_quality=20,
            ),
        ),
        DatasetRecord(
            dataset_id="worldclim",
            name="WorldClim / climat",
            description="Précipitations, température, bioclimatiques.",
            source="WorldClim",
            organization="WorldClim",
            official_url="https://www.worldclim.org/",
            license="CC-BY / conditions WorldClim",
            data_type="Raster climatique",
            format="GeoTIFF",
            coverage="Mondiale / RDC",
            resolution="~1 km (v2)",
            coordinate_reference_system="EPSG:4326",
            category="CLIMAT",
            data_class="OPEN",
            evidence_level="OBSERVATION",
            availability="NOT_CONNECTED",
            api_available="Téléchargement",
            access_method="Fichier — non synchronisé",
            frequency="Versions majeures",
            reliability_note="Interpolation climatique — pas une station locale",
            quality=_q(
                completeness=0,
                accuracy=65,
                consistency=70,
                recency=40,
                spatial_resolution=40,
                source_reliability=80,
                scientific_quality=75,
                processing_quality=20,
            ),
        ),
        DatasetRecord(
            dataset_id="cami",
            name="Cadastre Minier (CAMI)",
            description="Permis et concessions — source officielle RDC. Compass consomme, ne remplace pas.",
            source="CAMI / RDC",
            organization="CAMI / Ministère des Mines RDC",
            official_url="https://cami.cd/",
            license="Officiel RDC — usage réglementé",
            data_type="Permis / concessions",
            format="CSV / GeoJSON / GPKG / SHP / API",
            coverage="RDC",
            resolution="Vectoriel",
            coordinate_reference_system="À vérifier (souvent EPSG:4326)",
            category="MINIER / CADASTRE",
            data_class="OFFICIAL",
            evidence_level="OBSERVATION",
            availability="NOT_CONNECTED",
            api_available="À vérifier — pas d'API publique confirmée dans Compass",
            access_method="Import manuel / connecteur officiel uniquement",
            frequency="Selon publication CAMI",
            local_path="data/rdc/atlas/cadastre_permis.gpkg",
            last_data="Aucun export officiel chargé",
            reliability_note="Officiel UNIQUEMENT si export CAMI vérifié (pas DEMO-)",
            note=(
                "Le fichier local cadastre_permis.gpkg est une DÉMONSTRATION "
                "(préfixe DEMO). Concessions vérifiées = 0 sans export officiel."
            ),
            quality=_q(
                completeness=0,
                accuracy=20,
                consistency=40,
                recency=0,
                spatial_resolution=70,
                source_reliability=95,
                scientific_quality=80,
                processing_quality=30,
            ),
        ),
        DatasetRecord(
            dataset_id="pcm_extract_rdc",
            name="Extract RDC / PCM",
            description=(
                "Plateforme de Conformité Minière — couches cartographiques / conformité "
                "lorsque publiquement accessibles."
            ),
            source="Extract RDC / PCM",
            organization="Extract RDC / partenaires",
            official_url="https://www.extractrdc.org/",
            license="À confirmer selon jeu de données",
            data_type="Conformité / sites / cartes",
            format="Cartes / services / exports",
            coverage="RDC (selon publication)",
            resolution="Variable",
            coordinate_reference_system="N/E",
            category="MINIER / CONFORMITÉ",
            data_class="THIRD_PARTY",
            evidence_level="OBSERVATION",
            availability="NOT_CONNECTED",
            api_available="Non confirmée — aucune invention d'API",
            access_method="Mécanismes officiels uniquement lorsque disponibles",
            frequency="N/E",
            reliability_note="NOT_CONNECTED jusqu'à intégration autorisée",
            note="Connecteur extensible prévu — statut NOT_CONNECTED tant que non branché.",
            quality=_q(
                completeness=0,
                accuracy=0,
                consistency=0,
                recency=0,
                spatial_resolution=0,
                source_reliability=50,
                scientific_quality=40,
                processing_quality=0,
            ),
        ),
        DatasetRecord(
            dataset_id="drc_mining_warehouse",
            name="DRC Mining Data Warehouse",
            description=(
                "Entrepôt de données minières RDC — occurrences, exploration, historiques "
                "lorsque l'accès est autorisé."
            ),
            source="DRC Mining Data Warehouse",
            organization="DRC Mining / partenaires",
            official_url="",
            license="À confirmer — accès réglementé",
            data_type="Occurrences / mines / exploration",
            format="API / fichiers / services (selon accès)",
            coverage="RDC",
            resolution="Variable",
            coordinate_reference_system="N/E",
            category="MINIER / ENTREPÔT",
            data_class="THIRD_PARTY",
            evidence_level="OBSERVATION",
            availability="NOT_CONNECTED",
            api_available="Non confirmée dans Compass",
            access_method="Connecteur extensible — fetch/validate/normalize lorsque autorisé",
            frequency="N/E",
            reliability_note="NOT_CONNECTED — aucune donnée inventée",
            note="Documenter endpoints/licences avant tout import.",
            quality=_q(
                completeness=0,
                accuracy=0,
                consistency=0,
                recency=0,
                spatial_resolution=0,
                source_reliability=50,
                scientific_quality=50,
                processing_quality=0,
            ),
        ),
        DatasetRecord(
            dataset_id="usgs_mrds",
            name="USGS MRDS",
            description="Mineral Resources Data System — occurrences historiques (filtrer ISO=CD).",
            source="USGS",
            organization="USGS",
            official_url="https://mrdata.usgs.gov/mrds/",
            license="USGS public",
            data_type="Occurrences minérales",
            format="CSV / GeoJSON",
            coverage="Mondiale (filtrer COD)",
            resolution="Ponctuel",
            coordinate_reference_system="EPSG:4326",
            category="MINIER / OCCURRENCES",
            data_class="OPEN",
            evidence_level="OBSERVATION",
            availability="TO_CONFIGURE",
            api_available="Téléchargement",
            access_method="Import ISO=CD",
            frequency="Historique",
            last_data="Non importé",
            reliability_note="Open data historique — positions approximatives possibles",
            quality=_q(
                completeness=0,
                accuracy=55,
                consistency=50,
                recency=20,
                spatial_resolution=40,
                source_reliability=75,
                scientific_quality=60,
                processing_quality=20,
            ),
        ),
        DatasetRecord(
            dataset_id="atlas_compass",
            name="Atlas Compass (occurrences de référence)",
            description=(
                "Points de démonstration / références publiques approximatives — "
                "PAS un inventaire CAMI ni USGS importé."
            ),
            source="CriticalMineralsCompass (génération locale / références publiques)",
            organization="CriticalMineralsCompass",
            official_url="",
            license="Interne — démonstration",
            data_type="Occurrences (démo)",
            format="GPKG",
            coverage="RDC (points démo)",
            resolution="Ponctuel",
            coordinate_reference_system="EPSG:4326",
            category="MINIER / OCCURRENCES",
            data_class="DEMO",
            evidence_level="INTERPRETATION",
            availability="DEMO",
            api_available="Interne",
            access_method="Fichiers locaux data/rdc/atlas/",
            frequency="Génération locale",
            acquisition_date="2026-09",
            last_update="génération locale",
            local_path="data/rdc/atlas/",
            reliability_note="DÉMO — ne pas confondre avec cadastre ou MRDS officiel",
            note="data_source dans catalog.json corrigé : DEMO / synthèse locale.",
            quality=_q(
                completeness=40,
                accuracy=35,
                consistency=50,
                recency=60,
                spatial_resolution=40,
                source_reliability=30,
                scientific_quality=35,
                processing_quality=70,
            ),
        ),
        DatasetRecord(
            dataset_id="cadastre_demo",
            name="Cadastre permis (couche DEMO)",
            description="Polygones de permis générés pour démonstration UI — préfixe DEMO-.",
            source="CriticalMineralsCompass generate-atlas",
            organization="CriticalMineralsCompass",
            official_url="",
            license="Interne — démonstration",
            data_type="Permis fictifs",
            format="GPKG",
            coverage="Zones démo",
            resolution="Vectoriel",
            coordinate_reference_system="EPSG:4326",
            category="MINIER / CADASTRE",
            data_class="DEMO",
            evidence_level="INTERPRETATION",
            availability="DEMO",
            local_path="data/rdc/atlas/cadastre_permis.gpkg",
            api_available="Non",
            access_method="Fichier local",
            reliability_note="DÉMO — titulaire vide, jamais présenté comme CAMI officiel",
            note="Afficher toujours SOURCE TYPE: DEMO.",
            quality=_q(
                completeness=50,
                accuracy=20,
                consistency=60,
                recency=60,
                spatial_resolution=50,
                source_reliability=15,
                scientific_quality=20,
                processing_quality=80,
            ),
        ),
        DatasetRecord(
            dataset_id="kolwezi_stack",
            name="Stack multiphysique Kolwezi (échantillon)",
            description="Raster 64×64×8 synthétique pour pipeline MPM Cu-Co — zone pilote.",
            source="critical-compass generate-sample-data",
            organization="CriticalMineralsCompass",
            official_url="",
            license="Interne — synthétique",
            data_type="Raster multiphysique",
            format="GeoTIFF",
            coverage="~16×16 km Kolwezi (synthétique)",
            resolution="250 m (approx.)",
            coordinate_reference_system="EPSG:32733",
            category="GÉOPHYSIQUE / PILOTE",
            data_class="SYNTHETIC",
            evidence_level="PREDICTION",
            availability="SYNTHETIC",
            local_path="data/rdc/kolwezi/stack_multiphysics.tif",
            acquisition_date="seed=42",
            reliability_note="SYNTHÉTIQUE — pas des données Xcalibur/CAMI réelles",
            note="Permet de tester le pipeline sans données externes.",
            quality=_q(
                completeness=70,
                accuracy=30,
                consistency=80,
                recency=70,
                spatial_resolution=45,
                source_reliability=20,
                scientific_quality=25,
                processing_quality=85,
            ),
        ),
        DatasetRecord(
            dataset_id="worldpop",
            name="WorldPop COD",
            description="Densité de population — raster officiel ou proxy .npy démo.",
            source="WorldPop",
            organization="WorldPop",
            official_url="https://www.worldpop.org/geodata/country?iso=COD",
            license="À confirmer avant usage opérationnel",
            data_type="Densité population",
            format="GeoTIFF / npy",
            coverage="RDC",
            resolution="~100 m (officiel) / proxy démo",
            coordinate_reference_system="EPSG:4326",
            category="SOCIAL",
            data_class="ESTIMATED",
            evidence_level="INTERPRETATION",
            availability="DEMO",
            local_path="data/rdc/atlas/population_density.npy",
            api_available="Téléchargement",
            access_method="Fichier local",
            reliability_note="Estimation — proxy .npy ≠ raster WorldPop licence",
            quality=_q(
                completeness=30,
                accuracy=40,
                consistency=50,
                recency=40,
                spatial_resolution=35,
                source_reliability=50,
                scientific_quality=45,
                processing_quality=50,
            ),
        ),
        DatasetRecord(
            dataset_id="osm",
            name="OpenStreetMap",
            description="Routes, hydrographie, lieux — infrastructures et fond de carte.",
            source="OSM / contributeurs",
            organization="OpenStreetMap",
            official_url="https://www.openstreetmap.org/",
            license="ODbL",
            data_type="Routes, hydro, lieux",
            format="Tuiles / PBF",
            coverage="RDC",
            resolution="Vectoriel",
            coordinate_reference_system="EPSG:3857 (tuiles)",
            category="INFRASTRUCTURE",
            data_class="OPEN",
            evidence_level="OBSERVATION",
            availability="CONNECTED",
            api_available="Tuiles / Overpass",
            access_method="HTTP",
            frequency="Continu",
            last_data="Tuiles en ligne",
            reliability_note="Variable selon région — offline-safe",
            quality=_q(
                completeness=55,
                accuracy=60,
                consistency=55,
                recency=80,
                spatial_resolution=70,
                source_reliability=70,
                scientific_quality=50,
                processing_quality=70,
            ),
        ),
        DatasetRecord(
            dataset_id="favorability_woe",
            name="Raster prospectivité WoE (pilote Kolwezi)",
            description="Indice prédictif WoE Cu-Co — emprise d'entraînement uniquement.",
            source="CriticalMineralsCompass pipeline",
            organization="CriticalMineralsCompass",
            official_url="",
            license="Interne",
            data_type="Indice prédictif",
            format="GeoTIFF / npy",
            coverage="Zone pilote Kolwezi",
            resolution="Pixel d'entrée",
            coordinate_reference_system="EPSG:32733",
            category="PROSPECTIVITÉ / IA",
            data_class="PREDICTED",
            evidence_level="PREDICTION",
            availability="DEMO",
            local_path="outputs/kolwezi_sample/",
            api_available="API /api/prospectivity",
            access_method="Fichier local",
            frequency="À chaque run",
            reliability_note="Prédiction — pas un gisement confirmé",
            note="Hors emprise → N/E (jamais score 0 artificiel).",
            quality=_q(
                completeness=40,
                accuracy=45,
                consistency=70,
                recency=70,
                spatial_resolution=50,
                source_reliability=40,
                scientific_quality=55,
                processing_quality=80,
            ),
        ),
        DatasetRecord(
            dataset_id="regions_national",
            name="Référentiel provinces / bassins miniers",
            description="Métadonnées nationales provinces et bassins (JSON).",
            source="CriticalMineralsCompass",
            organization="CriticalMineralsCompass",
            official_url="",
            license="Interne",
            data_type="Référentiel administratif / métallogénique",
            format="JSON",
            coverage="RDC",
            resolution="Province / bassin",
            coordinate_reference_system="EPSG:4326",
            category="RÉFÉRENTIEL",
            data_class="DERIVED",
            evidence_level="INTERPRETATION",
            availability="LOCAL_OK",
            local_path="data/rdc/national/regions.json",
            reliability_note="Référentiel applicatif — pas un découpage administratif officiel CAMI",
            quality=_q(
                completeness=80,
                accuracy=70,
                consistency=85,
                recency=70,
                spatial_resolution=40,
                source_reliability=60,
                scientific_quality=55,
                processing_quality=90,
            ),
        ),
        DatasetRecord(
            dataset_id="geology_national",
            name="Géologie nationale (lithologie / failles)",
            description="Couches géologiques nationales — fichiers attendus non présents.",
            source="À intégrer (cartes géologiques RDC / open data)",
            organization="N/E",
            official_url="",
            license="N/E",
            data_type="Lithologie / structures",
            format="GPKG",
            coverage="RDC",
            resolution="N/E",
            coordinate_reference_system="EPSG:4326",
            category="GÉOLOGIE",
            data_class="UNAVAILABLE",
            evidence_level="OBSERVATION",
            availability="NOT_AVAILABLE",
            local_path="data/rdc/national/geology.gpkg",
            note="Fichiers geology.gpkg / faults.gpkg référencés mais absents.",
            reliability_note="N/E — donnée absente",
            quality=_q(
                completeness=0,
                accuracy=0,
                consistency=0,
                recency=0,
                spatial_resolution=0,
                source_reliability=0,
                scientific_quality=0,
                processing_quality=0,
            ),
        ),
        DatasetRecord(
            dataset_id="geochemistry",
            name="Géochimie (échantillons)",
            description="Points d'analyse élémentaire — module activable par import CSV.",
            source="Laboratoires / campagnes",
            organization="N/E",
            official_url="",
            license="Selon campagne",
            data_type="Échantillons géochimiques",
            format="CSV / GPKG",
            coverage="Selon import",
            resolution="Ponctuel",
            coordinate_reference_system="EPSG:4326",
            category="GÉOCHIMIE",
            data_class="UNAVAILABLE",
            evidence_level="OBSERVATION",
            availability="NOT_AVAILABLE",
            note="Importer CSV (élément, x, y, valeur, unité, labo, LOD) pour activer.",
            reliability_note="0 échantillon local",
            quality=_q(
                completeness=0,
                accuracy=0,
                consistency=0,
                recency=0,
                spatial_resolution=0,
                source_reliability=0,
                scientific_quality=0,
                processing_quality=0,
            ),
        ),
        DatasetRecord(
            dataset_id="geophysics_national",
            name="Géophysique nationale",
            description="Magnétisme, radiométrie, gravimétrie — hors stack Kolwezi synthétique.",
            source="À intégrer",
            organization="N/E",
            official_url="",
            license="N/E",
            data_type="Géophysique aéroportée / terrestre",
            format="GeoTIFF / GPKG",
            coverage="RDC",
            resolution="N/E",
            coordinate_reference_system="N/E",
            category="GÉOPHYSIQUE",
            data_class="UNAVAILABLE",
            evidence_level="OBSERVATION",
            availability="NOT_AVAILABLE",
            note="Le stack Kolwezi synthétique n'est pas une couverture nationale.",
            reliability_note="N/E",
            quality=_q(
                completeness=0,
                accuracy=0,
                consistency=0,
                recency=0,
                spatial_resolution=0,
                source_reliability=0,
                scientific_quality=0,
                processing_quality=0,
            ),
        ),
        DatasetRecord(
            dataset_id="drillholes_demo",
            name="Forages démo",
            description="Collars / intervals CSV de démonstration.",
            source="CriticalMineralsCompass",
            organization="CriticalMineralsCompass",
            official_url="",
            license="Interne — démonstration",
            data_type="Forages",
            format="CSV",
            coverage="Démo",
            resolution="Ponctuel",
            coordinate_reference_system="EPSG:4326",
            category="FORAGES",
            data_class="DEMO",
            evidence_level="OBSERVATION",
            availability="DEMO",
            local_path="data/rdc/demo/drillholes/",
            reliability_note="DÉMO",
            quality=_q(
                completeness=40,
                accuracy=30,
                consistency=60,
                recency=60,
                spatial_resolution=50,
                source_reliability=25,
                scientific_quality=30,
                processing_quality=70,
            ),
        ),
    ]
